#ifndef _FRAMEBUFFER_H
#define _FRAMEBUFFER_H

#define FRAMEBUFFER_BASE_ADDR  0xC0020000
#define FRAMEBUFFER_WIDTH  400
#define FRAMEBUFFER_HEIGHT  300
#define FRAMEBUFFER_LENGTH  (FRAMEBUFFER_WIDTH*FRAMEBUFFER_HEIGHT)

#endif // _FRAMEBUFFER_H
